name: Publish Docker GPU Images

on:
  push:
    branches:
    - master
    tags:
    - v*
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2880
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M')" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./gpu.Dockerfile
        platforms: linux/amd64
        push: true
        no-cache: true
        tags: |
          chwy907/odm:gpu-${{ env.BUILD_TIME }}
          chwy907/odm:gpu
